[sdk] Sync API
This is necessary to go past
FAILED: gen/zircon/public/lib/sync/sync_sdk_verify_api.verified
/usr/bin/env ../../build/testing/verify_golden_file.py --golden fuchsia/sdk/lib/sync/sync.api --current fuchsia/out/default/gen/zircon/public/lib/sync/sync_sdk.api --stamp fuchsia/out/default/gen/zircon/public/lib/sync/sync_sdk_verify_api.verified
Error: Golden file mismatch
Please acknowledge this change by running:
  cp fuchsia/out/default/gen/zircon/public/lib/sync/sync_sdk.api fuchsia/sdk/lib/sync/sync.api

Change-Id: I33a4b6a6e67552532210c20fbdac93cffcb959bc