[scripts] Fix build-qemu.sh
When compiling against the current master branch of
https://fuchsia.googlesource.com/third_party/qemu/ this is required to
go past
ERROR: unknown option --without-system-pixman
ERROR: unknown option --disable-bluez

Change-Id: Ib133fdb50f7ebb6107f8a94b7cf0305ea63a3176